version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    depends_on:
      - mysql
    networks: 
      - jornada-network
  
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: journeymile
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - jornada-network
  prometheus: 
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - jornada-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  nginx: 
    container_name: nginx
    depends_on: 
      - api
    ports: 
      - "8000:8000"
    build:
      context: ./nginx
    networks: 
      - jornada-network
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data

networks:
  jornada-network:
    driver: bridge
