// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
)

const createDestination = `-- name: CreateDestination :exec
INSERT INTO destinations (id, photo1, photo2, name, meta, text_description, price) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDestinationParams struct {
	ID              string
	Photo1          string
	Photo2          string
	Name            string
	Meta            string
	TextDescription string
	Price           float64
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, createDestination,
		arg.ID,
		arg.Photo1,
		arg.Photo2,
		arg.Name,
		arg.Meta,
		arg.TextDescription,
		arg.Price,
	)
	return err
}

const createTestimonial = `-- name: CreateTestimonial :exec
INSERT INTO testimonials (id, name, testimonial) VALUES (?, ?, ?)
`

type CreateTestimonialParams struct {
	ID          string
	Name        string
	Testimonial string
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) error {
	_, err := q.db.ExecContext(ctx, createTestimonial, arg.ID, arg.Name, arg.Testimonial)
	return err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = ?
`

func (q *Queries) DeleteDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDestination, id)
	return err
}

const deleteTestimonial = `-- name: DeleteTestimonial :exec
DELETE FROM testimonials WHERE id = ?
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTestimonial, id)
	return err
}

const getDestination = `-- name: GetDestination :many
SELECT id, photo1, photo2, name, meta, text_description, price FROM destinations ORDER BY name
`

type GetDestinationRow struct {
	ID              string
	Photo1          string
	Photo2          string
	Name            string
	Meta            string
	TextDescription string
	Price           float64
}

func (q *Queries) GetDestination(ctx context.Context) ([]GetDestinationRow, error) {
	rows, err := q.db.QueryContext(ctx, getDestination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDestinationRow
	for rows.Next() {
		var i GetDestinationRow
		if err := rows.Scan(
			&i.ID,
			&i.Photo1,
			&i.Photo2,
			&i.Name,
			&i.Meta,
			&i.TextDescription,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDestinationById = `-- name: GetDestinationById :one
SELECT id, photo1, photo2, name, meta, text_description, price FROM destinations WHERE id = ?
`

type GetDestinationByIdRow struct {
	ID              string
	Photo1          string
	Photo2          string
	Name            string
	Meta            string
	TextDescription string
	Price           float64
}

func (q *Queries) GetDestinationById(ctx context.Context, id string) (GetDestinationByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDestinationById, id)
	var i GetDestinationByIdRow
	err := row.Scan(
		&i.ID,
		&i.Photo1,
		&i.Photo2,
		&i.Name,
		&i.Meta,
		&i.TextDescription,
		&i.Price,
	)
	return i, err
}

const getDestinationsByName = `-- name: GetDestinationsByName :many
SELECT id, photo1, photo2, name, meta, text_description, price
FROM destinations
WHERE name LIKE CONCAT('%', ?, '%')
`

type GetDestinationsByNameRow struct {
	ID              string
	Photo1          string
	Photo2          string
	Name            string
	Meta            string
	TextDescription string
	Price           float64
}

func (q *Queries) GetDestinationsByName(ctx context.Context, concat interface{}) ([]GetDestinationsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getDestinationsByName, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDestinationsByNameRow
	for rows.Next() {
		var i GetDestinationsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Photo1,
			&i.Photo2,
			&i.Name,
			&i.Meta,
			&i.TextDescription,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestimonial = `-- name: GetTestimonial :many
SELECT id, name, testimonial FROM testimonials ORDER BY name
`

func (q *Queries) GetTestimonial(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.QueryContext(ctx, getTestimonial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(&i.ID, &i.Name, &i.Testimonial); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :exec
UPDATE destinations SET photo1 = ?, photo2 = ?, name = ?, meta = ?, text_description = ?, price = ? WHERE id = ?
`

type UpdateDestinationParams struct {
	Photo1          string
	Photo2          string
	Name            string
	Meta            string
	TextDescription string
	Price           float64
	ID              string
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateDestination,
		arg.Photo1,
		arg.Photo2,
		arg.Name,
		arg.Meta,
		arg.TextDescription,
		arg.Price,
		arg.ID,
	)
	return err
}

const updateTestimonial = `-- name: UpdateTestimonial :exec
UPDATE testimonials SET name = ?, testimonial = ? WHERE id = ?
`

type UpdateTestimonialParams struct {
	Name        string
	Testimonial string
	ID          string
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) error {
	_, err := q.db.ExecContext(ctx, updateTestimonial, arg.Name, arg.Testimonial, arg.ID)
	return err
}
