// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package db

import (
	"context"
)

const createDestination = `-- name: CreateDestination :exec
INSERT INTO destinations (id, name, price, photo) VALUES (?, ?, ?, ?)
`

type CreateDestinationParams struct {
	ID    string
	Name  string
	Price float64
	Photo string
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, createDestination,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Photo,
	)
	return err
}

const createTestimonial = `-- name: CreateTestimonial :exec
INSERT INTO testimonials (id, name, testimonial) VALUES (?, ?, ?)
`

type CreateTestimonialParams struct {
	ID          string
	Name        string
	Testimonial string
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) error {
	_, err := q.db.ExecContext(ctx, createTestimonial, arg.ID, arg.Name, arg.Testimonial)
	return err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = ?
`

func (q *Queries) DeleteDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDestination, id)
	return err
}

const deleteTestimonial = `-- name: DeleteTestimonial :exec
DELETE FROM testimonials WHERE id = ?
`

func (q *Queries) DeleteTestimonial(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTestimonial, id)
	return err
}

const getDestination = `-- name: GetDestination :many
SELECT id, name, price, photo FROM destinations ORDER BY name
`

func (q *Queries) GetDestination(ctx context.Context) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, getDestination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDestinationsByName = `-- name: GetDestinationsByName :many
SELECT id, name, price, photo
FROM destinations
WHERE name LIKE CONCAT('%', ?, '%')
`

func (q *Queries) GetDestinationsByName(ctx context.Context, concat interface{}) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, getDestinationsByName, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestimonial = `-- name: GetTestimonial :many
SELECT id, name, testimonial FROM testimonials ORDER BY name
`

func (q *Queries) GetTestimonial(ctx context.Context) ([]Testimonial, error) {
	rows, err := q.db.QueryContext(ctx, getTestimonial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Testimonial
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(&i.ID, &i.Name, &i.Testimonial); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :exec
UPDATE destinations SET name = ?, price = ?, photo = ? WHERE id = ?
`

type UpdateDestinationParams struct {
	Name  string
	Price float64
	Photo string
	ID    string
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateDestination,
		arg.Name,
		arg.Price,
		arg.Photo,
		arg.ID,
	)
	return err
}

const updateTestimonial = `-- name: UpdateTestimonial :exec
UPDATE testimonials SET name = ?, testimonial = ? WHERE id = ?
`

type UpdateTestimonialParams struct {
	Name        string
	Testimonial string
	ID          string
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) error {
	_, err := q.db.ExecContext(ctx, updateTestimonial, arg.Name, arg.Testimonial, arg.ID)
	return err
}
