// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Rafael Ribeiro",
            "email": "ribeirorafaelmatheus@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/depoimentos": {
            "get": {
                "description": "Get a list of all Testimonials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testimonials"
                ],
                "summary": "Retrieve all Testimonials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Testimonial"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a specific Testimonial",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testimonials"
                ],
                "summary": "Update a Testimonial",
                "parameters": [
                    {
                        "description": "TestimonialUpdateDTO",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/testimonials.TestimonialUpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Testimonial"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Testimonial",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testimonials"
                ],
                "summary": "Create a Testimonial",
                "parameters": [
                    {
                        "description": "TestimonialCreateDTO",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/testimonials.TestimonialCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Testimonial"
                        }
                    }
                }
            }
        },
        "/api/v1/depoimentos-home": {
            "get": {
                "description": "Get a list of three random Testimonials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testimonials"
                ],
                "summary": "Retrieve three random Testimonials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Testimonial"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/depoimentos/{id}": {
            "delete": {
                "description": "Delete a specific Testimonial",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testimonials"
                ],
                "summary": "Delete a Testimonial",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Testimonial ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/destinos": {
            "get": {
                "description": "Get list of destinations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "destinations"
                ],
                "summary": "Get list of destinations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Destinations"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update a destination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "destinations"
                ],
                "summary": "Update a destination",
                "parameters": [
                    {
                        "description": "DestinationUpdateDTO",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/destinations.DestinationsUpdateDTO"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Create a new destination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "destinations"
                ],
                "summary": "Create a new destination",
                "parameters": [
                    {
                        "description": "DestinationsCreateDTO",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/destinations.DestinationsCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Destinations"
                        }
                    }
                }
            }
        },
        "/api/v1/destinos/{id}": {
            "delete": {
                "description": "Delete a destination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "destinations"
                ],
                "summary": "Delete a destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/query/destinos": {
            "get": {
                "description": "Search destinations by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "destinations"
                ],
                "summary": "Search destinations by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination Name",
                        "name": "nome",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Destinations"
                            }
                        }
                    },
                    "404": {
                        "description": "mensagem\": \"Nenhum destino foi encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "destinations.DestinationsCreateDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "destinations.DestinationsUpdateDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "entity.Destinations": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "entity.Testimonial": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "testimonial": {
                    "type": "string"
                }
            }
        },
        "testimonials.TestimonialCreateDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "testimonial": {
                    "type": "string"
                }
            }
        },
        "testimonials.TestimonialUpdateDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "testimonial": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "Jorna Milha API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
